=== bonnysystems/website/.astro/collections/outreach.schema.json
{
  "$ref": "#/definitions/outreach",
  "definitions": {
    "outreach": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "recommended_pricing_plan": {
          "type": "string"
        },
        "website_url": {
          "type": "string"
        },
        "scores": {
          "type": "object",
          "properties": {
            "mobile": {
              "type": "object",
              "properties": {
                "design": {
                  "type": "number"
                },
                "performance": {
                  "type": "number"
                },
                "accessibility": {
                  "type": "number"
                },
                "seo": {
                  "type": "number"
                }
              },
              "required": [
                "design",
                "performance",
                "accessibility",
                "seo"
              ],
              "additionalProperties": false
            },
            "desktop": {
              "type": "object",
              "properties": {
                "design": {
                  "type": "number"
                },
                "performance": {
                  "type": "number"
                },
                "accessibility": {
                  "type": "number"
                },
                "seo": {
                  "type": "number"
                }
              },
              "required": [
                "design",
                "performance",
                "accessibility",
                "seo"
              ],
              "additionalProperties": false
            }
          },
          "required": [
            "mobile",
            "desktop"
          ],
          "additionalProperties": false
        },
        "outreached_at": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "recommended_pricing_plan"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== bonnysystems/website/src/content/outreach/f5qb.json
{
  "name": "Phlebotomy School Of NJ",
  "recommended_pricing_plan": "modern",
  "website_url": "https://phlebotomynj.com/",
  "scores": {
    "mobile": {
      "design": 40,
      "performance": 28,
      "accessibility": 82,
      "seo": 100
    },
    "desktop": {
      "design": 35,
      "performance": 27,
      "accessibility": 82,
      "seo": 100
    }
  },
  "outreached_at": "2024-03-21"
}

=== bonnysystems/website/src/content/outreach/djy9.json
{
  "name": "Silent Siren Tattoo",
  "recommended_pricing_plan": "fresh",
  "website_url": "https://silentsirentattoo.com",
  "scores": {
    "mobile": {
      "design": 40,
      "performance": 86,
      "accessibility": 93,
      "seo": 100
    },
    "desktop": {
      "design": 40,
      "performance": 91,
      "accessibility": 89,
      "seo": 100
    }
  },
  "outreached_at": "2024-03-21"
}

=== bonnysystems/website/src/content/outreach/gzu2.json
{
  "name": "DLA Realty & Management Co., LLC",
  "recommended_pricing_plan": "modern",
  "website_url": "http://www.dlarealty.com",
  "scores": {
    "mobile": {
      "design": 75,
      "performance": 30,
      "accessibility": 81,
      "seo": 82
    },
    "desktop": {
      "design": 55,
      "performance": 76,
      "accessibility": 89,
      "seo": 83
    }
  },
  "outreached_at": "2024-03-21"
}
