=== bonnysystems/website/.astro/collections/outreach.schema.json
{
  "$ref": "#/definitions/outreach",
  "definitions": {
    "outreach": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "recommended_pricing_plan": {
          "type": "string"
        },
        "website_url": {
          "type": "string"
        },
        "scores": {
          "type": "object",
          "properties": {
            "mobile": {
              "type": "object",
              "properties": {
                "design": {
                  "type": "number"
                },
                "performance": {
                  "type": "number"
                },
                "accessibility": {
                  "type": "number"
                },
                "seo": {
                  "type": "number"
                }
              },
              "required": [
                "design",
                "performance",
                "accessibility",
                "seo"
              ],
              "additionalProperties": false
            },
            "desktop": {
              "type": "object",
              "properties": {
                "design": {
                  "type": "number"
                },
                "performance": {
                  "type": "number"
                },
                "accessibility": {
                  "type": "number"
                },
                "seo": {
                  "type": "number"
                }
              },
              "required": [
                "design",
                "performance",
                "accessibility",
                "seo"
              ],
              "additionalProperties": false
            }
          },
          "required": [
            "mobile",
            "desktop"
          ],
          "additionalProperties": false
        },
        "outreached_at": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "recommended_pricing_plan"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== bonnysystems/website/src/content/outreach/acrv.json
{
  "name": "Center For Electrolysis and Skin Radiance",
  "recommended_pricing_plan": "fresh",
  "website_url": "https://www.skinradiancecenter.com",
  "scores": {
    "mobile": {
      "design": 12,
      "performance": 99,
      "accessibility": 81,
      "seo": 75
    },
    "desktop": {
      "design": 24,
      "performance": 100,
      "accessibility": 81,
      "seo": 90
    }
  }
}

=== bonnysystems/website/src/content/outreach/c2xe.json
{
  "name": "The Law Firm of Robert H. Altshuler",
  "recommended_pricing_plan": "modern",
  "website_url": "https://www.lawrha.com",
  "scores": {
    "mobile": {
      "design": 75,
      "performance": 26,
      "accessibility": 86,
      "seo": 79
    },
    "desktop": {
      "design": 70,
      "performance": 61,
      "accessibility": 86,
      "seo": 75
    }
  },
  "outreached_at": "2024-03-21"
}

=== bonnysystems/website/src/content/outreach/34dq.json
{
  "name": "Rovere Media",
  "recommended_pricing_plan": "fresh",
  "website_url": "https://roveremedia.com",
  "scores": {
    "mobile": {
      "design": 66,
      "performance": 29,
      "accessibility": 70,
      "seo": 79
    },
    "desktop": {
      "design": 47,
      "performance": 69,
      "accessibility": 77,
      "seo": 75
    }
  },
  "outreached_at": "2024-03-21"
}

=== bonnysystems/website/src/content/audits/silent-siren-tattoo.json
{
  "name": "Silent Siren Tattoo",
  "website_url": "silentsirentattoo.com",
  "scores": {
    "mobile": {
      "design": 40,
      "performance": 86,
      "accessibility": 93,
      "seo": 100
    },
    "desktop": {
      "design": 40,
      "performance": 91,
      "accessibility": 89,
      "seo": 100
    }
  },
  "recommended_pricing_plan": "fresh"
}

=== bonnysystems/website/src/content/outreach/love-your-look.json
{
  "name": "Love Your Look",
  "recommended_pricing_plan": "modern",
  "website_url": "https://www.loveyourlookbeautystudio.com",
  "scores": {
    "mobile": {
      "design": 35,
      "performance": 29,
      "accessibility": 85,
      "seo": 92
    },
    "desktop": {
      "design": 40,
      "performance": 80,
      "accessibility": 90,
      "seo": 92
    }
  }
}

=== bonnysystems/website/src/content/outreach/kc52.json
{
  "name": "Painters Plus Corporation",
  "recommended_pricing_plan": "fresh",
  "website_url": "http://www.painterspluscorp.com/",
  "scores": {
    "mobile": {
      "design": 10,
      "performance": 54,
      "accessibility": 87,
      "seo": 54
    },
    "desktop": {
      "design": 15,
      "performance": 85,
      "accessibility": 87,
      "seo": 64
    }
  },
  "outreached_at": "2024-03-21"
}

=== bonnysystems/website/src/content/outreach/r44f.json
{
  "name": "Home Therapy Solutions LLC",
  "recommended_pricing_plan": "fresh",
  "website_url": "https://www.hometherapysolutionsllc.com",
  "scores": {
    "mobile": {
      "design": 50,
      "performance": 49,
      "accessibility": 80,
      "seo": 85
    },
    "desktop": {
      "design": 57,
      "performance": 80,
      "accessibility": 80,
      "seo": 73
    }
  },
  "outreached_at": "2024-03-21"
}

=== bonnysystems/website/src/content/outreach/f2y6.json
{
  "name": "The Law Offices of A. Michael Rubin",
  "recommended_pricing_plan": "fresh",
  "website_url": "http://www.amrubin.com",
  "scores": {
    "mobile": {
      "design": 15,
      "performance": 70,
      "accessibility": 67,
      "seo": 67
    },
    "desktop": {
      "design": 30,
      "performance": 70,
      "accessibility": 67,
      "seo": 80
    }
  },
  "outreached_at": "2024-03-21"
}
